name = "Jak & Daxter"
home = "https://discord.com/channels/731205301247803413/1138467653552451606"

[versions]
"0.1.1" = { url = "https://github.com/ArchipelaGOAL/Archipelago/releases/download/beta-v0.1.1/jakanddaxter.apworld" }
